// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTask.proto

#include "ProtoTask.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Role::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Role::Role(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RoleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoleDefaultTypeInternal() {}
  union {
    Role _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoleDefaultTypeInternal _Role_default_instance_;

inline constexpr PerformanceTestRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : resbody_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        someid_{::int64_t{0}},
        someidadd_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PerformanceTestRes::PerformanceTestRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PerformanceTestResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PerformanceTestResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PerformanceTestResDefaultTypeInternal() {}
  union {
    PerformanceTestRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PerformanceTestResDefaultTypeInternal _PerformanceTestRes_default_instance_;

inline constexpr PerformanceTestReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : somebody_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        someid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PerformanceTestReq::PerformanceTestReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PerformanceTestReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PerformanceTestReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PerformanceTestReqDefaultTypeInternal() {}
  union {
    PerformanceTestReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PerformanceTestReqDefaultTypeInternal _PerformanceTestReq_default_instance_;

inline constexpr LogoutResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : errorcode_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogoutResponse::LogoutResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LogoutResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogoutResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogoutResponseDefaultTypeInternal() {}
  union {
    LogoutResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogoutResponseDefaultTypeInternal _LogoutResponse_default_instance_;

inline constexpr LogoutRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sessionid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogoutRequest::LogoutRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LogoutRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogoutRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogoutRequestDefaultTypeInternal() {}
  union {
    LogoutRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogoutRequestDefaultTypeInternal _LogoutRequest_default_instance_;

inline constexpr LoginResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : servertime_{::int64_t{0}},
        roleid_{::int64_t{0}},
        errorcode_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginResponse::LoginResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginResponseDefaultTypeInternal() {}
  union {
    LoginResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginResponseDefaultTypeInternal _LoginResponse_default_instance_;

inline constexpr LoginRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : logintoken_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accountid_{::int64_t{0}},
        roleid_{::int64_t{0}},
        gameticket_{0},
        serverid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginRequest::LoginRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginRequestDefaultTypeInternal() {}
  union {
    LoginRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginRequestDefaultTypeInternal _LoginRequest_default_instance_;

inline constexpr ItemProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : itemid_{0},
        count_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ItemProto::ItemProto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ItemProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemProtoDefaultTypeInternal() {}
  union {
    ItemProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemProtoDefaultTypeInternal _ItemProto_default_instance_;

inline constexpr IntIntProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : intvalue1_{0},
        intvalue2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IntIntProto::IntIntProto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct IntIntProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntIntProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntIntProtoDefaultTypeInternal() {}
  union {
    IntIntProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntIntProtoDefaultTypeInternal _IntIntProto_default_instance_;

inline constexpr EchoReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : requestbody_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        someid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EchoReq::EchoReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EchoReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoReqDefaultTypeInternal() {}
  union {
    EchoReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoReqDefaultTypeInternal _EchoReq_default_instance_;
static ::_pb::Metadata file_level_metadata_ProtoTask_2eproto[10];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ProtoTask_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ProtoTask_2eproto = nullptr;
const ::uint32_t TableStruct_ProtoTask_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::IntIntProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::IntIntProto, _impl_.intvalue1_),
    PROTOBUF_FIELD_OFFSET(::IntIntProto, _impl_.intvalue2_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Role, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Role, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::Role, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ItemProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ItemProto, _impl_.itemid_),
    PROTOBUF_FIELD_OFFSET(::ItemProto, _impl_.count_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _impl_.accountid_),
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _impl_.roleid_),
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _impl_.logintoken_),
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _impl_.gameticket_),
    PROTOBUF_FIELD_OFFSET(::LoginRequest, _impl_.serverid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LoginResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::LoginResponse, _impl_.errorcode_),
    PROTOBUF_FIELD_OFFSET(::LoginResponse, _impl_.servertime_),
    PROTOBUF_FIELD_OFFSET(::LoginResponse, _impl_.roleid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LogoutRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::LogoutRequest, _impl_.sessionid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LogoutResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::LogoutResponse, _impl_.errorcode_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PerformanceTestReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PerformanceTestReq, _impl_.someid_),
    PROTOBUF_FIELD_OFFSET(::PerformanceTestReq, _impl_.somebody_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PerformanceTestRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PerformanceTestRes, _impl_.someid_),
    PROTOBUF_FIELD_OFFSET(::PerformanceTestRes, _impl_.resbody_),
    PROTOBUF_FIELD_OFFSET(::PerformanceTestRes, _impl_.someidadd_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::EchoReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::EchoReq, _impl_.requestbody_),
    PROTOBUF_FIELD_OFFSET(::EchoReq, _impl_.someid_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::IntIntProto)},
        {10, -1, -1, sizeof(::Role)},
        {20, -1, -1, sizeof(::ItemProto)},
        {30, -1, -1, sizeof(::LoginRequest)},
        {43, -1, -1, sizeof(::LoginResponse)},
        {54, -1, -1, sizeof(::LogoutRequest)},
        {63, -1, -1, sizeof(::LogoutResponse)},
        {72, -1, -1, sizeof(::PerformanceTestReq)},
        {82, -1, -1, sizeof(::PerformanceTestRes)},
        {93, -1, -1, sizeof(::EchoReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_IntIntProto_default_instance_._instance,
    &::_Role_default_instance_._instance,
    &::_ItemProto_default_instance_._instance,
    &::_LoginRequest_default_instance_._instance,
    &::_LoginResponse_default_instance_._instance,
    &::_LogoutRequest_default_instance_._instance,
    &::_LogoutResponse_default_instance_._instance,
    &::_PerformanceTestReq_default_instance_._instance,
    &::_PerformanceTestRes_default_instance_._instance,
    &::_EchoReq_default_instance_._instance,
};
const char descriptor_table_protodef_ProtoTask_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017ProtoTask.proto\"3\n\013IntIntProto\022\021\n\tintV"
    "alue1\030\001 \001(\005\022\021\n\tintValue2\030\002 \001(\005\" \n\004Role\022\n"
    "\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\"*\n\tItemProto\022\016\n"
    "\006itemId\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\"k\n\014LoginReq"
    "uest\022\021\n\taccountId\030\001 \001(\003\022\016\n\006roleId\030\002 \001(\003\022"
    "\022\n\nloginToken\030\003 \001(\t\022\022\n\ngameTicket\030\004 \001(\005\022"
    "\020\n\010serverId\030\005 \001(\005\"F\n\rLoginResponse\022\021\n\ter"
    "rorCode\030\001 \001(\005\022\022\n\nserverTime\030\002 \001(\003\022\016\n\006rol"
    "eId\030\003 \001(\003\"\"\n\rLogoutRequest\022\021\n\tsessionId\030"
    "\001 \001(\003\"#\n\016LogoutResponse\022\021\n\terrorCode\030\001 \001"
    "(\005\"6\n\022PerformanceTestReq\022\016\n\006someId\030\001 \001(\003"
    "\022\020\n\010someBody\030\002 \001(\t\"H\n\022PerformanceTestRes"
    "\022\016\n\006someId\030\001 \001(\003\022\017\n\007resBody\030\002 \001(\t\022\021\n\tsom"
    "eIdAdd\030\003 \001(\003\".\n\007EchoReq\022\023\n\013requestBody\030\001"
    " \001(\t\022\016\n\006someId\030\002 \001(\003B\033\n\016com.game.protoZ\t"
    "/protoGenb\006proto3"
};
static ::absl::once_flag descriptor_table_ProtoTask_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ProtoTask_2eproto = {
    false,
    false,
    617,
    descriptor_table_protodef_ProtoTask_2eproto,
    "ProtoTask.proto",
    &descriptor_table_ProtoTask_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_ProtoTask_2eproto::offsets,
    file_level_metadata_ProtoTask_2eproto,
    file_level_enum_descriptors_ProtoTask_2eproto,
    file_level_service_descriptors_ProtoTask_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ProtoTask_2eproto_getter() {
  return &descriptor_table_ProtoTask_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ProtoTask_2eproto(&descriptor_table_ProtoTask_2eproto);
// ===================================================================

class IntIntProto::_Internal {
 public:
};

IntIntProto::IntIntProto(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:IntIntProto)
}
IntIntProto::IntIntProto(
    ::google::protobuf::Arena* arena, const IntIntProto& from)
    : IntIntProto(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IntIntProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IntIntProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, intvalue1_),
           0,
           offsetof(Impl_, intvalue2_) -
               offsetof(Impl_, intvalue1_) +
               sizeof(Impl_::intvalue2_));
}
IntIntProto::~IntIntProto() {
  // @@protoc_insertion_point(destructor:IntIntProto)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void IntIntProto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void IntIntProto::Clear() {
// @@protoc_insertion_point(message_clear_start:IntIntProto)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.intvalue1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.intvalue2_) -
      reinterpret_cast<char*>(&_impl_.intvalue1_)) + sizeof(_impl_.intvalue2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* IntIntProto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> IntIntProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_IntIntProto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 intValue2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntIntProto, _impl_.intvalue2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue2_)}},
    // int32 intValue1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IntIntProto, _impl_.intvalue1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 intValue1 = 1;
    {PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 intValue2 = 2;
    {PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* IntIntProto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntIntProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 intValue1 = 1;
  if (this->_internal_intvalue1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_intvalue1(), target);
  }

  // int32 intValue2 = 2;
  if (this->_internal_intvalue2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_intvalue2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntIntProto)
  return target;
}

::size_t IntIntProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntIntProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 intValue1 = 1;
  if (this->_internal_intvalue1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_intvalue1());
  }

  // int32 intValue2 = 2;
  if (this->_internal_intvalue2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_intvalue2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData IntIntProto::_class_data_ = {
    IntIntProto::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* IntIntProto::GetClassData() const {
  return &_class_data_;
}

void IntIntProto::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<IntIntProto*>(&to_msg);
  auto& from = static_cast<const IntIntProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:IntIntProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_intvalue1() != 0) {
    _this->_internal_set_intvalue1(from._internal_intvalue1());
  }
  if (from._internal_intvalue2() != 0) {
    _this->_internal_set_intvalue2(from._internal_intvalue2());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IntIntProto::CopyFrom(const IntIntProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntIntProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool IntIntProto::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* IntIntProto::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void IntIntProto::InternalSwap(IntIntProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue2_)
      + sizeof(IntIntProto::_impl_.intvalue2_)
      - PROTOBUF_FIELD_OFFSET(IntIntProto, _impl_.intvalue1_)>(
          reinterpret_cast<char*>(&_impl_.intvalue1_),
          reinterpret_cast<char*>(&other->_impl_.intvalue1_));
}

::google::protobuf::Metadata IntIntProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[0]);
}
// ===================================================================

class Role::_Internal {
 public:
};

Role::Role(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Role)
}
inline PROTOBUF_NDEBUG_INLINE Role::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Role::Role(
    ::google::protobuf::Arena* arena,
    const Role& from)
    : ::google::protobuf::Message(arena) {
  Role* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:Role)
}
inline PROTOBUF_NDEBUG_INLINE Role::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Role::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Role::~Role() {
  // @@protoc_insertion_point(destructor:Role)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Role::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Role::Clear() {
// @@protoc_insertion_point(message_clear_start:Role)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.id_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Role::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 17, 2> Role::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Role_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Role, _impl_.name_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Role, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Role, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(Role, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(Role, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\4\0\4\0\0\0\0\0"
    "Role"
    "name"
  }},
};

::uint8_t* Role::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Role)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Role.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Role)
  return target;
}

::size_t Role::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Role)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Role::_class_data_ = {
    Role::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Role::GetClassData() const {
  return &_class_data_;
}

void Role::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Role*>(&to_msg);
  auto& from = static_cast<const Role&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Role)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Role::CopyFrom(const Role& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Role)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Role::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Role::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Role::InternalSwap(Role* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Role::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[1]);
}
// ===================================================================

class ItemProto::_Internal {
 public:
};

ItemProto::ItemProto(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ItemProto)
}
ItemProto::ItemProto(
    ::google::protobuf::Arena* arena, const ItemProto& from)
    : ItemProto(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ItemProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ItemProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, itemid_),
           0,
           offsetof(Impl_, count_) -
               offsetof(Impl_, itemid_) +
               sizeof(Impl_::count_));
}
ItemProto::~ItemProto() {
  // @@protoc_insertion_point(destructor:ItemProto)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ItemProto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ItemProto::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemProto)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.itemid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.count_) -
      reinterpret_cast<char*>(&_impl_.itemid_)) + sizeof(_impl_.count_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ItemProto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ItemProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ItemProto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 count = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ItemProto, _impl_.count_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.count_)}},
    // int32 itemId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ItemProto, _impl_.itemid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.itemid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 itemId = 1;
    {PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.itemid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 count = 2;
    {PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ItemProto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ItemProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 itemId = 1;
  if (this->_internal_itemid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_itemid(), target);
  }

  // int32 count = 2;
  if (this->_internal_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ItemProto)
  return target;
}

::size_t ItemProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ItemProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 itemId = 1;
  if (this->_internal_itemid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_itemid());
  }

  // int32 count = 2;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ItemProto::_class_data_ = {
    ItemProto::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ItemProto::GetClassData() const {
  return &_class_data_;
}

void ItemProto::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ItemProto*>(&to_msg);
  auto& from = static_cast<const ItemProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ItemProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_itemid() != 0) {
    _this->_internal_set_itemid(from._internal_itemid());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ItemProto::CopyFrom(const ItemProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ItemProto::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ItemProto::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ItemProto::InternalSwap(ItemProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.count_)
      + sizeof(ItemProto::_impl_.count_)
      - PROTOBUF_FIELD_OFFSET(ItemProto, _impl_.itemid_)>(
          reinterpret_cast<char*>(&_impl_.itemid_),
          reinterpret_cast<char*>(&other->_impl_.itemid_));
}

::google::protobuf::Metadata ItemProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[2]);
}
// ===================================================================

class LoginRequest::_Internal {
 public:
};

LoginRequest::LoginRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LoginRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoginRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : logintoken_(arena, from.logintoken_),
        _cached_size_{0} {}

LoginRequest::LoginRequest(
    ::google::protobuf::Arena* arena,
    const LoginRequest& from)
    : ::google::protobuf::Message(arena) {
  LoginRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, accountid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, accountid_),
           offsetof(Impl_, serverid_) -
               offsetof(Impl_, accountid_) +
               sizeof(Impl_::serverid_));

  // @@protoc_insertion_point(copy_constructor:LoginRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoginRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : logintoken_(arena),
        _cached_size_{0} {}

inline void LoginRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, accountid_),
           0,
           offsetof(Impl_, serverid_) -
               offsetof(Impl_, accountid_) +
               sizeof(Impl_::serverid_));
}
LoginRequest::~LoginRequest() {
  // @@protoc_insertion_point(destructor:LoginRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.logintoken_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LoginRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:LoginRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.logintoken_.ClearToEmpty();
  ::memset(&_impl_.accountid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.serverid_) -
      reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.serverid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 31, 2> LoginRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 accountId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LoginRequest, _impl_.accountid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.accountid_)}},
    // int64 roleId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LoginRequest, _impl_.roleid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.roleid_)}},
    // string loginToken = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.logintoken_)}},
    // int32 gameTicket = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginRequest, _impl_.gameticket_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.gameticket_)}},
    // int32 serverId = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginRequest, _impl_.serverid_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.serverid_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 accountId = 1;
    {PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.accountid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 roleId = 2;
    {PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.roleid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string loginToken = 3;
    {PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.logintoken_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 gameTicket = 4;
    {PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.gameticket_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 serverId = 5;
    {PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.serverid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\14\0\0\12\0\0\0\0"
    "LoginRequest"
    "loginToken"
  }},
};

::uint8_t* LoginRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoginRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 accountId = 1;
  if (this->_internal_accountid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_accountid(), target);
  }

  // int64 roleId = 2;
  if (this->_internal_roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_roleid(), target);
  }

  // string loginToken = 3;
  if (!this->_internal_logintoken().empty()) {
    const std::string& _s = this->_internal_logintoken();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LoginRequest.loginToken");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 gameTicket = 4;
  if (this->_internal_gameticket() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_gameticket(), target);
  }

  // int32 serverId = 5;
  if (this->_internal_serverid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_serverid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LoginRequest)
  return target;
}

::size_t LoginRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LoginRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string loginToken = 3;
  if (!this->_internal_logintoken().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_logintoken());
  }

  // int64 accountId = 1;
  if (this->_internal_accountid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_accountid());
  }

  // int64 roleId = 2;
  if (this->_internal_roleid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_roleid());
  }

  // int32 gameTicket = 4;
  if (this->_internal_gameticket() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_gameticket());
  }

  // int32 serverId = 5;
  if (this->_internal_serverid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_serverid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LoginRequest::_class_data_ = {
    LoginRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LoginRequest::GetClassData() const {
  return &_class_data_;
}

void LoginRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LoginRequest*>(&to_msg);
  auto& from = static_cast<const LoginRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoginRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_logintoken().empty()) {
    _this->_internal_set_logintoken(from._internal_logintoken());
  }
  if (from._internal_accountid() != 0) {
    _this->_internal_set_accountid(from._internal_accountid());
  }
  if (from._internal_roleid() != 0) {
    _this->_internal_set_roleid(from._internal_roleid());
  }
  if (from._internal_gameticket() != 0) {
    _this->_internal_set_gameticket(from._internal_gameticket());
  }
  if (from._internal_serverid() != 0) {
    _this->_internal_set_serverid(from._internal_serverid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginRequest::CopyFrom(const LoginRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoginRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LoginRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LoginRequest::InternalSwap(LoginRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.logintoken_, &other->_impl_.logintoken_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.serverid_)
      + sizeof(LoginRequest::_impl_.serverid_)
      - PROTOBUF_FIELD_OFFSET(LoginRequest, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

::google::protobuf::Metadata LoginRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[3]);
}
// ===================================================================

class LoginResponse::_Internal {
 public:
};

LoginResponse::LoginResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LoginResponse)
}
LoginResponse::LoginResponse(
    ::google::protobuf::Arena* arena, const LoginResponse& from)
    : LoginResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LoginResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LoginResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, servertime_),
           0,
           offsetof(Impl_, errorcode_) -
               offsetof(Impl_, servertime_) +
               sizeof(Impl_::errorcode_));
}
LoginResponse::~LoginResponse() {
  // @@protoc_insertion_point(destructor:LoginResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:LoginResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.servertime_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.errorcode_) -
      reinterpret_cast<char*>(&_impl_.servertime_)) + sizeof(_impl_.errorcode_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> LoginResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 errorCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginResponse, _impl_.errorcode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.errorcode_)}},
    // int64 serverTime = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LoginResponse, _impl_.servertime_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.servertime_)}},
    // int64 roleId = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LoginResponse, _impl_.roleid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.roleid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 errorCode = 1;
    {PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 serverTime = 2;
    {PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.servertime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 roleId = 3;
    {PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.roleid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* LoginResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoginResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 errorCode = 1;
  if (this->_internal_errorcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_errorcode(), target);
  }

  // int64 serverTime = 2;
  if (this->_internal_servertime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_servertime(), target);
  }

  // int64 roleId = 3;
  if (this->_internal_roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_roleid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LoginResponse)
  return target;
}

::size_t LoginResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LoginResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 serverTime = 2;
  if (this->_internal_servertime() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_servertime());
  }

  // int64 roleId = 3;
  if (this->_internal_roleid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_roleid());
  }

  // int32 errorCode = 1;
  if (this->_internal_errorcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_errorcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LoginResponse::_class_data_ = {
    LoginResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LoginResponse::GetClassData() const {
  return &_class_data_;
}

void LoginResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LoginResponse*>(&to_msg);
  auto& from = static_cast<const LoginResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoginResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_servertime() != 0) {
    _this->_internal_set_servertime(from._internal_servertime());
  }
  if (from._internal_roleid() != 0) {
    _this->_internal_set_roleid(from._internal_roleid());
  }
  if (from._internal_errorcode() != 0) {
    _this->_internal_set_errorcode(from._internal_errorcode());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginResponse::CopyFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LoginResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LoginResponse::InternalSwap(LoginResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.errorcode_)
      + sizeof(LoginResponse::_impl_.errorcode_)
      - PROTOBUF_FIELD_OFFSET(LoginResponse, _impl_.servertime_)>(
          reinterpret_cast<char*>(&_impl_.servertime_),
          reinterpret_cast<char*>(&other->_impl_.servertime_));
}

::google::protobuf::Metadata LoginResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[4]);
}
// ===================================================================

class LogoutRequest::_Internal {
 public:
};

LogoutRequest::LogoutRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LogoutRequest)
}
LogoutRequest::LogoutRequest(
    ::google::protobuf::Arena* arena, const LogoutRequest& from)
    : LogoutRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LogoutRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LogoutRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sessionid_ = {};
}
LogoutRequest::~LogoutRequest() {
  // @@protoc_insertion_point(destructor:LogoutRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LogoutRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LogoutRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:LogoutRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sessionid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LogoutRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LogoutRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LogoutRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 sessionId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LogoutRequest, _impl_.sessionid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LogoutRequest, _impl_.sessionid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 sessionId = 1;
    {PROTOBUF_FIELD_OFFSET(LogoutRequest, _impl_.sessionid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* LogoutRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LogoutRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 sessionId = 1;
  if (this->_internal_sessionid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_sessionid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LogoutRequest)
  return target;
}

::size_t LogoutRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LogoutRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 sessionId = 1;
  if (this->_internal_sessionid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_sessionid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LogoutRequest::_class_data_ = {
    LogoutRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LogoutRequest::GetClassData() const {
  return &_class_data_;
}

void LogoutRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LogoutRequest*>(&to_msg);
  auto& from = static_cast<const LogoutRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LogoutRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sessionid() != 0) {
    _this->_internal_set_sessionid(from._internal_sessionid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LogoutRequest::CopyFrom(const LogoutRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LogoutRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LogoutRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LogoutRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LogoutRequest::InternalSwap(LogoutRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sessionid_, other->_impl_.sessionid_);
}

::google::protobuf::Metadata LogoutRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[5]);
}
// ===================================================================

class LogoutResponse::_Internal {
 public:
};

LogoutResponse::LogoutResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LogoutResponse)
}
LogoutResponse::LogoutResponse(
    ::google::protobuf::Arena* arena, const LogoutResponse& from)
    : LogoutResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LogoutResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LogoutResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.errorcode_ = {};
}
LogoutResponse::~LogoutResponse() {
  // @@protoc_insertion_point(destructor:LogoutResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LogoutResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LogoutResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:LogoutResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errorcode_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LogoutResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LogoutResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LogoutResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 errorCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LogoutResponse, _impl_.errorcode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LogoutResponse, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 errorCode = 1;
    {PROTOBUF_FIELD_OFFSET(LogoutResponse, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* LogoutResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LogoutResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 errorCode = 1;
  if (this->_internal_errorcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_errorcode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LogoutResponse)
  return target;
}

::size_t LogoutResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LogoutResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 errorCode = 1;
  if (this->_internal_errorcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_errorcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LogoutResponse::_class_data_ = {
    LogoutResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LogoutResponse::GetClassData() const {
  return &_class_data_;
}

void LogoutResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LogoutResponse*>(&to_msg);
  auto& from = static_cast<const LogoutResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LogoutResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_errorcode() != 0) {
    _this->_internal_set_errorcode(from._internal_errorcode());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LogoutResponse::CopyFrom(const LogoutResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LogoutResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LogoutResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LogoutResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LogoutResponse::InternalSwap(LogoutResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.errorcode_, other->_impl_.errorcode_);
}

::google::protobuf::Metadata LogoutResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[6]);
}
// ===================================================================

class PerformanceTestReq::_Internal {
 public:
};

PerformanceTestReq::PerformanceTestReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PerformanceTestReq)
}
inline PROTOBUF_NDEBUG_INLINE PerformanceTestReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : somebody_(arena, from.somebody_),
        _cached_size_{0} {}

PerformanceTestReq::PerformanceTestReq(
    ::google::protobuf::Arena* arena,
    const PerformanceTestReq& from)
    : ::google::protobuf::Message(arena) {
  PerformanceTestReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.someid_ = from._impl_.someid_;

  // @@protoc_insertion_point(copy_constructor:PerformanceTestReq)
}
inline PROTOBUF_NDEBUG_INLINE PerformanceTestReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : somebody_(arena),
        _cached_size_{0} {}

inline void PerformanceTestReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.someid_ = {};
}
PerformanceTestReq::~PerformanceTestReq() {
  // @@protoc_insertion_point(destructor:PerformanceTestReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PerformanceTestReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.somebody_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PerformanceTestReq::Clear() {
// @@protoc_insertion_point(message_clear_start:PerformanceTestReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.somebody_.ClearToEmpty();
  _impl_.someid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PerformanceTestReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 35, 2> PerformanceTestReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PerformanceTestReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string someBody = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PerformanceTestReq, _impl_.somebody_)}},
    // int64 someId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PerformanceTestReq, _impl_.someid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PerformanceTestReq, _impl_.someid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 someId = 1;
    {PROTOBUF_FIELD_OFFSET(PerformanceTestReq, _impl_.someid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string someBody = 2;
    {PROTOBUF_FIELD_OFFSET(PerformanceTestReq, _impl_.somebody_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\10\0\0\0\0\0"
    "PerformanceTestReq"
    "someBody"
  }},
};

::uint8_t* PerformanceTestReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PerformanceTestReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 someId = 1;
  if (this->_internal_someid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_someid(), target);
  }

  // string someBody = 2;
  if (!this->_internal_somebody().empty()) {
    const std::string& _s = this->_internal_somebody();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PerformanceTestReq.someBody");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PerformanceTestReq)
  return target;
}

::size_t PerformanceTestReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PerformanceTestReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string someBody = 2;
  if (!this->_internal_somebody().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_somebody());
  }

  // int64 someId = 1;
  if (this->_internal_someid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_someid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PerformanceTestReq::_class_data_ = {
    PerformanceTestReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PerformanceTestReq::GetClassData() const {
  return &_class_data_;
}

void PerformanceTestReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PerformanceTestReq*>(&to_msg);
  auto& from = static_cast<const PerformanceTestReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PerformanceTestReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_somebody().empty()) {
    _this->_internal_set_somebody(from._internal_somebody());
  }
  if (from._internal_someid() != 0) {
    _this->_internal_set_someid(from._internal_someid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PerformanceTestReq::CopyFrom(const PerformanceTestReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PerformanceTestReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PerformanceTestReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PerformanceTestReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PerformanceTestReq::InternalSwap(PerformanceTestReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.somebody_, &other->_impl_.somebody_, arena);
        swap(_impl_.someid_, other->_impl_.someid_);
}

::google::protobuf::Metadata PerformanceTestReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[7]);
}
// ===================================================================

class PerformanceTestRes::_Internal {
 public:
};

PerformanceTestRes::PerformanceTestRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PerformanceTestRes)
}
inline PROTOBUF_NDEBUG_INLINE PerformanceTestRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : resbody_(arena, from.resbody_),
        _cached_size_{0} {}

PerformanceTestRes::PerformanceTestRes(
    ::google::protobuf::Arena* arena,
    const PerformanceTestRes& from)
    : ::google::protobuf::Message(arena) {
  PerformanceTestRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, someid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, someid_),
           offsetof(Impl_, someidadd_) -
               offsetof(Impl_, someid_) +
               sizeof(Impl_::someidadd_));

  // @@protoc_insertion_point(copy_constructor:PerformanceTestRes)
}
inline PROTOBUF_NDEBUG_INLINE PerformanceTestRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : resbody_(arena),
        _cached_size_{0} {}

inline void PerformanceTestRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, someid_),
           0,
           offsetof(Impl_, someidadd_) -
               offsetof(Impl_, someid_) +
               sizeof(Impl_::someidadd_));
}
PerformanceTestRes::~PerformanceTestRes() {
  // @@protoc_insertion_point(destructor:PerformanceTestRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PerformanceTestRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.resbody_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PerformanceTestRes::Clear() {
// @@protoc_insertion_point(message_clear_start:PerformanceTestRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resbody_.ClearToEmpty();
  ::memset(&_impl_.someid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.someidadd_) -
      reinterpret_cast<char*>(&_impl_.someid_)) + sizeof(_impl_.someidadd_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PerformanceTestRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 34, 2> PerformanceTestRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PerformanceTestRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 someId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PerformanceTestRes, _impl_.someid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someid_)}},
    // string resBody = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.resbody_)}},
    // int64 someIdAdd = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PerformanceTestRes, _impl_.someidadd_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someidadd_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 someId = 1;
    {PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string resBody = 2;
    {PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.resbody_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 someIdAdd = 3;
    {PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someidadd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\22\0\7\0\0\0\0\0"
    "PerformanceTestRes"
    "resBody"
  }},
};

::uint8_t* PerformanceTestRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PerformanceTestRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 someId = 1;
  if (this->_internal_someid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_someid(), target);
  }

  // string resBody = 2;
  if (!this->_internal_resbody().empty()) {
    const std::string& _s = this->_internal_resbody();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PerformanceTestRes.resBody");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int64 someIdAdd = 3;
  if (this->_internal_someidadd() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_someidadd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PerformanceTestRes)
  return target;
}

::size_t PerformanceTestRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PerformanceTestRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string resBody = 2;
  if (!this->_internal_resbody().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_resbody());
  }

  // int64 someId = 1;
  if (this->_internal_someid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_someid());
  }

  // int64 someIdAdd = 3;
  if (this->_internal_someidadd() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_someidadd());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PerformanceTestRes::_class_data_ = {
    PerformanceTestRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PerformanceTestRes::GetClassData() const {
  return &_class_data_;
}

void PerformanceTestRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PerformanceTestRes*>(&to_msg);
  auto& from = static_cast<const PerformanceTestRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PerformanceTestRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_resbody().empty()) {
    _this->_internal_set_resbody(from._internal_resbody());
  }
  if (from._internal_someid() != 0) {
    _this->_internal_set_someid(from._internal_someid());
  }
  if (from._internal_someidadd() != 0) {
    _this->_internal_set_someidadd(from._internal_someidadd());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PerformanceTestRes::CopyFrom(const PerformanceTestRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PerformanceTestRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PerformanceTestRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PerformanceTestRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PerformanceTestRes::InternalSwap(PerformanceTestRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.resbody_, &other->_impl_.resbody_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someidadd_)
      + sizeof(PerformanceTestRes::_impl_.someidadd_)
      - PROTOBUF_FIELD_OFFSET(PerformanceTestRes, _impl_.someid_)>(
          reinterpret_cast<char*>(&_impl_.someid_),
          reinterpret_cast<char*>(&other->_impl_.someid_));
}

::google::protobuf::Metadata PerformanceTestRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[8]);
}
// ===================================================================

class EchoReq::_Internal {
 public:
};

EchoReq::EchoReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EchoReq)
}
inline PROTOBUF_NDEBUG_INLINE EchoReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : requestbody_(arena, from.requestbody_),
        _cached_size_{0} {}

EchoReq::EchoReq(
    ::google::protobuf::Arena* arena,
    const EchoReq& from)
    : ::google::protobuf::Message(arena) {
  EchoReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.someid_ = from._impl_.someid_;

  // @@protoc_insertion_point(copy_constructor:EchoReq)
}
inline PROTOBUF_NDEBUG_INLINE EchoReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : requestbody_(arena),
        _cached_size_{0} {}

inline void EchoReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.someid_ = {};
}
EchoReq::~EchoReq() {
  // @@protoc_insertion_point(destructor:EchoReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EchoReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.requestbody_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void EchoReq::Clear() {
// @@protoc_insertion_point(message_clear_start:EchoReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.requestbody_.ClearToEmpty();
  _impl_.someid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* EchoReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 27, 2> EchoReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EchoReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 someId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(EchoReq, _impl_.someid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(EchoReq, _impl_.someid_)}},
    // string requestBody = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EchoReq, _impl_.requestbody_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string requestBody = 1;
    {PROTOBUF_FIELD_OFFSET(EchoReq, _impl_.requestbody_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 someId = 2;
    {PROTOBUF_FIELD_OFFSET(EchoReq, _impl_.someid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\7\13\0\0\0\0\0\0"
    "EchoReq"
    "requestBody"
  }},
};

::uint8_t* EchoReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EchoReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string requestBody = 1;
  if (!this->_internal_requestbody().empty()) {
    const std::string& _s = this->_internal_requestbody();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EchoReq.requestBody");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int64 someId = 2;
  if (this->_internal_someid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_someid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EchoReq)
  return target;
}

::size_t EchoReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EchoReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string requestBody = 1;
  if (!this->_internal_requestbody().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_requestbody());
  }

  // int64 someId = 2;
  if (this->_internal_someid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_someid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData EchoReq::_class_data_ = {
    EchoReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* EchoReq::GetClassData() const {
  return &_class_data_;
}

void EchoReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<EchoReq*>(&to_msg);
  auto& from = static_cast<const EchoReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EchoReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_requestbody().empty()) {
    _this->_internal_set_requestbody(from._internal_requestbody());
  }
  if (from._internal_someid() != 0) {
    _this->_internal_set_someid(from._internal_someid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EchoReq::CopyFrom(const EchoReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EchoReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EchoReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* EchoReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void EchoReq::InternalSwap(EchoReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.requestbody_, &other->_impl_.requestbody_, arena);
        swap(_impl_.someid_, other->_impl_.someid_);
}

::google::protobuf::Metadata EchoReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtoTask_2eproto_getter, &descriptor_table_ProtoTask_2eproto_once,
      file_level_metadata_ProtoTask_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
